name: Build
on:
    pull_request:      
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                echo "hello" > coverage.xml
                echo "world" >> junit.xml
            - name: Save test results for future steps
              uses: actions/upload-artifact@v3
              with:
               name: test-results
               path: |
                 ./junit.xml
                 ./coverage.xml                    